name: mebabl_core
description: Core SDK infrastructure for Mebabl Platform.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0