name: mebabl_core
description: Core SDK package for Mebabl platform, providing configuration, secure token storage, and a robust HTTP client for Flutter applications.
version: 1.0.5
repository: https://github.com/aliMerdan110/mebabl_core # أضف هذا السطر


environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0