name: mebabl_auth
description: Authentication SDK package for Mebabl platform, built on top of mebabl_core.
version: 1.0.0
repository: https://github.com/aliMerdan110/mebabl_auth

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  mebabl_core: ^1.0.0 # <--- الربط بالحزمة المنشورة

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0